version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: Proxy
    privileged: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/srv/docker/nginx-proxy-with-encrypt/certs:/etc/nginx/certs:ro'
      - '/srv/docker/nginx-proxy-with-encrypt/htpasswd:/etc/nginx/htpasswd:z'
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/srv/docker/nginx-proxy-with-encrypt/log:/var/log/nginx:z'
      - './proxy/server.conf:/etc/nginx/conf.d/server.conf:z'
    networks:
      app_net:
        ipv4_address: 192.168.56.100
      ssl_proxy:

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    container_name: letsencrypt-nginx
    privileged: true
    restart: always
    depends_on:
      - proxy
    volumes:
      - '/srv/docker/nginx-proxy-with-encrypt/certs:/etc/nginx/certs:z'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - proxy
    networks:
      app_net:
        ipv4_address: 192.168.56.101

  gitlab:
    image: gitlab/gitlab-ce:14.5.2-ce.0
    container_name: GitLab
    hostname: ${GITLAB_HOSTNAME}
    privileged: true
    restart: always
    environment:
      - VIRTUAL_HOST=${GITLAB_HOSTNAME}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${GITLAB_HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
    volumes:
      - '/srv/docker/gitlab/config:/etc/gitlab:z'
      - '/srv/docker/gitlab/logs:/var/log/gitlab:z'
      - '/srv/docker/gitlab/data:/var/opt/gitlab:z'
    ports:
      - "20022:22"
    networks:
      app_net:
        ipv4_address: 192.168.56.2

  wordpress:
    image: wordpress:5.7.0-apache
    container_name: WordPress
    hostname: ${WORDPRESS_HOSTNAME}
    privileged: true
    restart: always
    environment:
      - VIRTUAL_HOST=${WORDPRESS_HOSTNAME}
      - VIRTUAL_PORT=80
      - WORDPRESS_DB_HOST=wpmysql:3306
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_MYSQL}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USERNAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - LETSENCRYPT_HOST=${WORDPRESS_HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
    volumes:
      - '/srv/docker/wordpress/wp-content:/var/www/html/wp-content'
      - './wordpress/php.ini:/usr/local/etc/php/php.ini'
    networks:
      app_net:
        ipv4_address: 192.168.56.6

  wpmysql:
    image: mysql:8.0
    container_name: WordPressDB
    command: '--default-authentication-plugin=mysql_native_password'
    privileged: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_MYSQL}
      - MYSQL_USER=${WORDPRESS_DB_USERNAME}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - '/srv/docker/wpmysql:/var/lib/mysql:z'
    networks:
      app_net:
        ipv4_address: 192.168.56.7

networks:
  ssl_proxy:
    external: true
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24
          gateway: 192.168.56.1
