version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: Proxy
    privileged: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/srv/docker/nginx-proxy-with-encrypt/certs:/etc/nginx/certs:ro'
      - '/srv/docker/nginx-proxy-with-encrypt/htpasswd:/etc/nginx/htpasswd:z'
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/srv/docker/nginx-proxy-with-encrypt/log:/var/log/nginx:z'
      - './proxy/server.conf:/etc/nginx/conf.d/server.conf:z'
    networks:
      app_net:
        ipv4_address: 192.168.56.100
      ssl_proxy:

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
    privileged: true
    restart: always
    depends_on:
      - proxy
    volumes:
      - '/srv/docker/nginx-proxy-with-encrypt/certs:/etc/nginx/certs:z'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - proxy
    networks:
      app_net:
        ipv4_address: 192.168.56.101

#  open-ldap:
#    image: osixia/openldap
#    container_name: OpenLDAP
#    restart: always
#    environment:
#      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
#    Volumes:
#      - '/srv/docker/open-ldap/var/lib/ldap:/var/lib/ldap:z'
#      - '/srv/docker/open-ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d:z'
#    networks:
#      app_net:
#        ipv4_address: 192.168.56.102

#  ldap-admin:
#    image: osixia/phpldapadmin
#    container_name: phpLDAPadmin
#    restart: always
#    environment:
#      - VIRTUAL_HOST=${LDAPADMIN_HOSTNAME}
#      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=${LDAPADMIN_HOSTNAME}
#      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
#      - PHPLDAPADMIN_LDAP_HOSTS=${LDAPADMIN_HOSTNAME}
#      - PHPLDAPADMIN_HTTPS=false
#    volumes:
#      - '/srv/docker/ldap-admin/config:/container/service/phpldapadmin/assets/config:z'
#    links:
#      - open-ldap
#    networks:
#      app_net:
#        ipv4_address: 192.168.56.103

  gitlab:
    image: gitlab/gitlab-ce
    container_name: GitLab
    privileged: true
    restart: always
    environment:
      - VIRTUAL_HOST=${GITLAB_HOSTNAME}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${GITLAB_HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
    volumes:
      - '/srv/docker/gitlab/config:/cetc/gitlab:z'
      - '/srv/docker/gitlab/logs:/var/log/gitlab:z'
      - '/srv/docker/gitlab/data:/var/opt/gitlab:z'
    extra_hosts:
      - 'Jenkins:192.168.56.10'
      - '${JENKINS_HOSTNAME}:192.168.56.10'
    networks:
      app_net:
        ipv4_address: 192.168.56.2

  jupyterhub:
    build: ./jupyterhub/
    container_name: JupyterHub
    privileged: true
    restart: always
    environment:
      - VIRTUAL_HOST=${JUPYTERHUB_HOSTNAME}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${JUPYTERHUB_HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
      - GITLAB_HOST=http://${GITLAB_HOSTNAME}/
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
    volumes:
      - '/srv/docker/jupyter/data:/home:z'
    extra_hosts:
      - 'GitLab:192.168.56.2'
      - '${GITLAB_HOSTNAME}:192.168.56.2'
    networks:
      app_net:
        ipv4_address: 192.168.56.3

  redmine:
    image: redmine
    container_name: Redmine
    privileged: true
    restart: always
    environment:
      - REDMINE_DB_POSTGRES=${REDMINE_DB_POSTGRES}
      - REDMINE_DB_USERNAME=${REDMINE_DB_USERNAME}
      - REDMINE_DB_PASSWORD=${REDMINE_DB_PASSWORD}
      - VIRTUAL_HOST=${REDMINE_HOSTNAME}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${REDMINE_HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
    volumes:
      - '/srv/docker/redmine/files:/usr/src/redmine/files:z'
      - '/srv/docker/redmine/plugins:/usr/src/redmine/plugins:z'
      - '/srv/docker/redmine/vplugins:/usr/src/redmine/vendor/plugins:z'
      - '/srv/docker/redmine/themes:/usr/src/redmine/public/themes:z'
      - './redmine/redmine-theme-gitmike:/usr/src/redmine/public/themes/gitmike'
    links:
      - redminepg:postgres
#      - open-ldap:ldap
    networks:
      app_net:
        ipv4_address: 192.168.56.4

  redminepg:
    image: postgres:10.7
    container_name: RedmineDB

    environment:
      - POSTGRES_PASSWORD=${REDMINE_DB_PASSWORD}
      - POSTGRES_USER=${REDMINE_DB_USERNAME}
    volumes:
      - '/srv/docker/redminepg/data:/var/lib/postgresql/data:z'
    networks:
      app_net:
        ipv4_address: 192.168.56.5

  wordpress:
    image: wordpress
    container_name: WordPress
    privileged: true
    restart: always
    environment:
      - VIRTUAL_HOST=${WORDPRESS_HOSTNAME}
      - VIRTUAL_PORT=80
      - WORDPRESS_DB_HOST=wpmysql:3306
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_MYSQL}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USERNAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - LETSENCRYPT_HOST=${WORDPRESS_HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
    volumes:
      - '/srv/docker/wordpress/wp-content:/var/www/html/wp-content'
      - './wordpress/php.ini:/usr/local/etc/php/php.ini'
    networks:
      app_net:
        ipv4_address: 192.168.56.6

  wpmysql:
    image: mysql:8.0
    container_name: WordPressDB
    command: '--default-authentication-plugin=mysql_native_password'
    privileged: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_MYSQL}
      - MYSQL_USER=${WORDPRESS_DB_USERNAME}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - '/srv/docker/wpmysql:/var/lib/mysql:z'
#      - './wpmysql/my.cnf:/etc/mysql/my.cnf'
    networks:
      app_net:
        ipv4_address: 192.168.56.7

  jenkins:
    image: jenkinsci/blueocean
    container_name: Jenkins
#    privileged: true
    restart: always
    environment:
      - VIRTUAL_HOST=${JENKINS_HOSTNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${JENKINS_HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_ADDRESS}
    volumes:
      - '/srv/docker/jenkins:/var/jenkins_home:z'
    extra_hosts:
      - 'GitLab:192.168.56.2'
      - '${GITLAB_HOSTNAME}:192.168.56.2'
    networks:
      app_net:
        ipv4_address: 192.168.56.10
      slave-net:
        ipv4_address: 192.168.60.50

networks:
  ssl_proxy:
    external: true
  slave-net:
    external: true
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24
          gateway: 192.168.56.1
